POST http://localhost:3001/api/clients/signup HTTP/1.1
Content-Type: application/json

{
    
    "fullName": "Ehsan Ansari ",
     "phoneNumber": "1236678",
     "email": "ansari@email.com",
     "password":"Ciaociao1234",
     "address": "via giacinto,22 Torino, 10127",
     "wallet": 0
}