POST http://localhost:3001/api/clients/signup HTTP/1.1
Content-Type: application/json

{
    
    "fullName": "Vincenzo Di Stasio",
     "phoneNumber": "1236678223",
     "email": "Vincenzo2@email.com",
     "password":"Ciaociao1234",
     "address": "via giacinto,22 Torino, 10127",
     "wallet": 0
}